#!/usr/bin/env python3
"""Render Profile/people.md and the publications table in Profile/README.md
from the YAML files in Profile/data/.

Those two markdown files are what GitHub shows on the organisation page. They
are generated so they can never drift from the data the website is built from.
Edit Profile/data/*.yml — never the generated markdown.

Usage:
    python scripts/render_markdown.py           # write the files
    python scripts/render_markdown.py --check   # validate only, non-zero on error

Requires PyYAML (preinstalled on GitHub-hosted runners).
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "Profile" / "data"
PEOPLE_MD = ROOT / "Profile" / "people.md"
README_MD = ROOT / "Profile" / "README.md"

BANNER = (
    "<!-- ============================================================\n"
    "     AUTO-GENERATED — DO NOT EDIT THIS FILE BY HAND.\n"
    "     Source: Profile/data/people.yml\n"
    "     Regenerate: python scripts/render_markdown.py\n"
    "     ============================================================ -->\n"
)

PUB_TABLE_START = "<!-- PUBLICATIONS:START -->"
PUB_TABLE_END = "<!-- PUBLICATIONS:END -->"


def load(name: str):
    with (DATA / name).open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)


# --------------------------------------------------------------------------
# validation
# --------------------------------------------------------------------------

def validate(site, people, pubs, projects) -> list[str]:
    errors: list[str] = []

    role_keys = {r["key"] for r in site.get("roles", [])}
    theme_keys = set(site.get("themes") or {})
    person_ids: set[str] = set()

    for person in people:
        who = person.get("name", "<unnamed>")
        for required in ("id", "name", "title", "role"):
            if not person.get(required):
                errors.append(f"person {who!r}: missing required field {required!r}")
        pid = person.get("id")
        if pid in person_ids:
            errors.append(f"duplicate person id {pid!r}")
        person_ids.add(pid)

        if person.get("role") not in role_keys:
            errors.append(
                f"person {who!r}: role {person.get('role')!r} is not a key in site.yml -> roles"
            )
        photo = person.get("photo")
        if photo and not (ROOT / "Profile" / "Images" / photo).exists():
            errors.append(f"person {who!r}: photo Profile/Images/{photo} not found")

    for pub in pubs:
        title = str(pub.get("title", "<untitled>"))[:50]
        for required in ("year", "title", "authors"):
            if not pub.get(required):
                errors.append(f"publication {title!r}: missing required field {required!r}")
        if pub.get("theme") and pub["theme"] not in theme_keys:
            errors.append(
                f"publication {title!r}: theme {pub['theme']!r} is not a key in site.yml -> themes"
            )

    for theme in projects:
        key = theme.get("key")
        if key not in theme_keys:
            errors.append(f"project {key!r}: not a key in site.yml -> themes")
        for pid in theme.get("people") or []:
            if pid not in person_ids:
                errors.append(f"project {key!r}: unknown person id {pid!r}")

    # An opening disappears from the site by itself once its closing_date has
    # passed, so that date is load-bearing: written in any other format the
    # website's date comparison cannot read it, and the post either vanishes
    # at once or advertises a job nobody can apply for.
    for i, post in enumerate(site.get("openings") or [], start=1):
        closing = post.get("closing_date")
        if closing in (None, ""):
            continue
        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", str(closing)):
            title = str(post.get("title", "<untitled>")).strip()[:50]
            errors.append(
                f"opening {i} ({title!r}): closing_date {closing!r} is not "
                'ISO — write it as "YYYY-MM-DD", in quotes'
            )

    return errors


def validate_excluded() -> list[str]:
    """Check the sweep's exclusion list parses and is shaped as it expects.

    Deliberately separate from validate(): this file feeds
    scripts/fetch_publications.py rather than anything rendered here, and it
    is edited by hand more often than the rest, since a person decides what is
    out of scope.
    """
    path = DATA / "publications-excluded.yml"
    if not path.exists():
        return []  # absent is fine — the sweep creates it on first use.

    try:
        entries = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        # The usual cause is an entry indented under the one above it, which
        # makes "- year:" a sequence item where a mapping key is expected.
        # Every entry must start at column 0.
        return [f"will not parse, so the sweep cannot run: {exc}"]

    if entries is None:
        return []  # comments only, no entries yet.
    if not isinstance(entries, list):
        return [f"should be a list of entries, got {type(entries).__name__}"]

    errors: list[str] = []
    for i, entry in enumerate(entries, start=1):
        if not isinstance(entry, dict):
            errors.append(
                f"entry {i} is a {type(entry).__name__}, not a mapping — "
                "check its indentation"
            )
            continue
        # The DOI is the whole point: it is what the sweep matches on to avoid
        # re-proposing something. An entry without one is silently inert.
        if not (entry.get("doi") or "").strip():
            title = str(entry.get("title", "<untitled>"))[:60]
            errors.append(f"entry {i} ({title!r}) has no doi, so it will be re-proposed")
    return errors


# --------------------------------------------------------------------------
# people.md
# --------------------------------------------------------------------------

LINK_LABELS = {
    "website": "Website",
    "scholar": "Google Scholar",
    "orcid": "ORCID",
    "durham": "Durham profile",
    "github": "GitHub",
    "linkedin": "LinkedIn",
}


def clean(text: str | None) -> str:
    """Collapse a folded YAML block into a single paragraph."""
    if not text:
        return ""
    return re.sub(r"\s+", " ", str(text)).strip()


def render_person(person) -> str:
    out: list[str] = []
    out.append(f"### {person['name']} — {person['title']}")
    out.append("")

    if person.get("photo"):
        out.append(
            f'<img src="./Images/{person["photo"]}" alt="{person["name"]}" width="180">'
        )
        out.append("")

    meta = []
    if person.get("department"):
        meta.append(person["department"])
    meta.append("Durham University")
    out.append(", ".join(meta) + "  ")

    links = []
    if person.get("email"):
        links.append(f"[{person['email']}](mailto:{person['email']})")
    for key, url in (person.get("links") or {}).items():
        if url:
            links.append(f"[{LINK_LABELS.get(key, key.title())}]({url})")
    if links:
        out.append(" · ".join(links))
    out.append("")

    if person.get("bio"):
        out.append(f"> {clean(person['bio'])}")
        out.append("")
    if person.get("project"):
        out.append(f"> **Research project**: {clean(person['project'])}")
        out.append("")
    if person.get("roles_extra"):
        out.append("> " + " · ".join(person["roles_extra"]))
        out.append("")
    if person.get("supervisors"):
        out.append("> **Academic supervisors**: " + ", ".join(person["supervisors"]))
        out.append("")
    if person.get("alum_note"):
        out.append(f"> {clean(person['alum_note'])}")
        out.append("")

    return "\n".join(out)


def render_people_md(site, people) -> str:
    by_role: dict[str, list] = {}
    for person in people:
        by_role.setdefault(person["role"], []).append(person)

    out = [BANNER, "# 👥 People", ""]
    out.append(clean(site.get("intro")))
    out.append("")

    for role in site.get("roles", []):
        members = by_role.get(role["key"])
        if not members:
            continue
        out.append(f"## {role['label']}")
        out.append("")
        if clean(role.get("blurb")):
            out.append(clean(role["blurb"]))
            out.append("")
        for person in members:
            out.append(render_person(person))
            out.append("---")
            out.append("")

    out.append("## 💬 Enquiries & Opportunities")
    out.append("")
    out.append(
        "We welcome collaboration, and enquiries from prospective students and "
        "researchers interested in wind energy, atmospheric turbulence and "
        "environmental fluid mechanics — including those coming from applied "
        "mathematics, machine learning or data science rather than classical "
        "fluid dynamics."
    )
    out.append("")
    out.append(
        "There is no central inbox. Write to whichever of us works closest to "
        "what interests you — email addresses are listed above."
    )
    out.append("")
    if site.get("url"):
        out.append(f"🌐 [{site['url']}]({site['url']})")
        out.append("")

    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------
# README.md publications table
# --------------------------------------------------------------------------

def render_pub_table(pubs) -> str:
    rows = [
        PUB_TABLE_START,
        "<!-- Generated from Profile/data/publications.yml — do not edit by hand. -->",
        "",
        "| Year | Title | Authors | Publication | Code |",
        "|------|-------|---------|-------------|------|",
    ]
    ordered = sorted(pubs, key=lambda p: (-int(p["year"]), str(p["title"])))
    for pub in ordered:
        title = str(pub["title"]).replace("|", "\\|")
        authors = str(pub["authors"]).replace("|", "\\|")
        venue = str(pub.get("venue", "")).replace("|", "\\|")
        link = f"[{venue}]({pub['doi']})" if pub.get("doi") else venue
        code = f"[repo]({pub['repo']})" if pub.get("repo") else "—"
        rows.append(f"| {pub['year']} | **{title}** | {authors} | {link} | {code} |")
    rows.append("")
    rows.append(PUB_TABLE_END)
    return "\n".join(rows)


def splice_readme(text: str, table: str) -> str:
    if PUB_TABLE_START in text and PUB_TABLE_END in text:
        pattern = re.compile(
            re.escape(PUB_TABLE_START) + r".*?" + re.escape(PUB_TABLE_END),
            re.DOTALL,
        )
        return pattern.sub(lambda _: table, text)
    raise SystemExit(
        f"README.md is missing the {PUB_TABLE_START} / {PUB_TABLE_END} markers; "
        "cannot splice the publications table."
    )


# --------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="validate the data files without writing anything",
    )
    args = parser.parse_args()

    site = load("site.yml")
    people = load("people.yml")
    pubs = load("publications.yml")
    projects = load("projects.yml")

    # publications-excluded.yml is the publication sweep's memory, and the
    # sweep reads it before it does anything else. Nothing here renders from
    # it, but it is checked anyway: a hand-edit that breaks its YAML stops the
    # weekly sweep dead, and because the sweep is the thing that would have
    # told you about new papers, the site just quietly stops gaining them.
    # This has already happened once. Fail here, on push, where it is obvious.
    excluded_errors = validate_excluded()
    if excluded_errors:
        print("publications-excluded.yml is not usable:", file=sys.stderr)
        for err in excluded_errors:
            print(f"  - {err}", file=sys.stderr)
        return 1

    errors = validate(site, people, pubs, projects)
    if errors:
        print("Data validation failed:", file=sys.stderr)
        for err in errors:
            print(f"  - {err}", file=sys.stderr)
        return 1

    print(
        f"Validated {len(people)} people, {len(pubs)} publications, "
        f"{len(projects)} research themes."
    )
    if args.check:
        return 0

    PEOPLE_MD.write_text(render_people_md(site, people), encoding="utf-8")
    print(f"Wrote {PEOPLE_MD.relative_to(ROOT)}")

    readme = README_MD.read_text(encoding="utf-8")
    README_MD.write_text(splice_readme(readme, render_pub_table(pubs)), encoding="utf-8")
    print(f"Updated the publications table in {README_MD.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
